spring:
  application:
    name: dynamic-mapping-server

  jpa:
    properties:
      hibernate:
        event:
          merge:
            entity_copy_observer: allow
        
backing-services:
  network-store-server:
    preloading-strategy: COLLECTION

powsybl-ws:
  database:
    name: dynamicmappings
