spring:
  application:
    name: dynamic-mapping-server

  jpa:
    properties:
      hibernate:
        event:
          merge:
            entity_copy_observer: allow
        
network-store-server:
  preloading-strategy: COLLECTION

dbName: dynamicmappings
