server:
  port: 5036

powsybl:
  services:
    case-server:
      base-uri: http://localhost:5000
    network-conversion-server:
      base-uri: http://localhost:5003
    network-store-server:
      base-uri: http://localhost:8080/

powsybl-ws:
  database:
    host: localhost

# when perform a local test, fill by the path that contains external automaton resource files in json format
# e.g. /home/<user>/dynamic-mapping-resources/automaton
ex-resources:
  automaton:

