server:
  port: 5036

backing-services:
  case-server:
    base-uri: http://localhost:5000
  network-conversion-server:
    base-uri: http://localhost:5003
  network-store-server:
    base-uri: http://localhost:8080/

powsybl-ws:
  database:
    host: localhost
