-- parameters for IEEE57 model

INSERT INTO model_sets_group (model_name, name, type)
VALUES ('GeneratorSynchronousFourWindingsProportionalRegulations', 'IEEE57', 1);

INSERT INTO model_parameter_sets (group_name, group_type, model_name, name)
VALUES ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'IEEE57_GEN____6_SM');

INSERT INTO model_parameters (group_name, group_type, model_name, name, set_name, value_)
VALUES ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_ExcitationPu', 'IEEE57_GEN____6_SM', 1),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_md', 'IEEE57_GEN____6_SM', 0.084),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_mq', 'IEEE57_GEN____6_SM', 0.084),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_nd', 'IEEE57_GEN____6_SM', 5.57),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_nq', 'IEEE57_GEN____6_SM', 5.57),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_MdPuEfd', 'IEEE57_GEN____6_SM', 0),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_DPu', 'IEEE57_GEN____6_SM', 0),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_H', 'IEEE57_GEN____6_SM', 5.4),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_RaPu', 'IEEE57_GEN____6_SM', 0.00357),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_XlPu', 'IEEE57_GEN____6_SM', 0.219),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_XdPu', 'IEEE57_GEN____6_SM', 2.57),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_XpdPu', 'IEEE57_GEN____6_SM', 0.407),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_XppdPu', 'IEEE57_GEN____6_SM', 0.3),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_Tpd0', 'IEEE57_GEN____6_SM', 9.651),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_Tppd0', 'IEEE57_GEN____6_SM', 0.058),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_XqPu', 'IEEE57_GEN____6_SM', 2.57),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_XpqPu', 'IEEE57_GEN____6_SM', 0.454),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_XppqPu', 'IEEE57_GEN____6_SM', 0.301),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_Tpq0', 'IEEE57_GEN____6_SM', 1.0009),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_Tppq0', 'IEEE57_GEN____6_SM', 0.06),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_UNom', 'IEEE57_GEN____6_SM', 24),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_SNom', 'IEEE57_GEN____6_SM', 1120),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_PNomTurb', 'IEEE57_GEN____6_SM', 1008),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_PNomAlt', 'IEEE57_GEN____6_SM', 1008),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_SnTfo', 'IEEE57_GEN____6_SM', 1120),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_UNomHV', 'IEEE57_GEN____6_SM', 69),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_UNomLV', 'IEEE57_GEN____6_SM', 24),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_UBaseHV', 'IEEE57_GEN____6_SM', 69),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_UBaseLV', 'IEEE57_GEN____6_SM', 24),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_RTfPu', 'IEEE57_GEN____6_SM', 0.0),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_XTfPu', 'IEEE57_GEN____6_SM', 0.1),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'governor_KGover', 'IEEE57_GEN____6_SM', 5),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'governor_PMin', 'IEEE57_GEN____6_SM', 0),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'governor_PMax', 'IEEE57_GEN____6_SM', 1008),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'governor_PNom', 'IEEE57_GEN____6_SM', 1008),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'Pm_ValueIn', 'IEEE57_GEN____6_SM', 0),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'URef_ValueIn', 'IEEE57_GEN____6_SM', 0),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'voltageRegulator_EfdMinPu', 'IEEE57_GEN____6_SM', -5),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'voltageRegulator_EfdMaxPu', 'IEEE57_GEN____6_SM', 5),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'voltageRegulator_UsRefMinPu', 'IEEE57_GEN____6_SM', 0.8),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'voltageRegulator_UsRefMaxPu', 'IEEE57_GEN____6_SM', 1.5),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'voltageRegulator_Gain', 'IEEE57_GEN____6_SM', 20),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'voltageRegulator_LagEfdMin', 'IEEE57_GEN____6_SM', 0),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'voltageRegulator_LagEfdMax', 'IEEE57_GEN____6_SM', 0);

INSERT INTO model_parameters (group_name, group_type, model_name, name, set_name)
VALUES ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_P0Pu', 'IEEE57_GEN____6_SM'),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_Q0Pu', 'IEEE57_GEN____6_SM'),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_U0Pu', 'IEEE57_GEN____6_SM'),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_UPhase0', 'IEEE57_GEN____6_SM');

INSERT INTO model_parameter_sets (group_name, group_type, model_name, name)
VALUES ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'IEEE57_GEN____9_SM');

INSERT INTO model_parameters (group_name, group_type, model_name, name, set_name, value_)
VALUES ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_ExcitationPu', 'IEEE57_GEN____9_SM', 1),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_md', 'IEEE57_GEN____9_SM', 0.05),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_mq', 'IEEE57_GEN____9_SM', 0.05),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_nd', 'IEEE57_GEN____9_SM', 9.285),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_nq', 'IEEE57_GEN____9_SM', 9.285),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_MdPuEfd', 'IEEE57_GEN____9_SM', 0),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_DPu', 'IEEE57_GEN____9_SM', 0),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_H', 'IEEE57_GEN____9_SM', 5.625),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_RaPu', 'IEEE57_GEN____9_SM', 0.00316),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_XlPu', 'IEEE57_GEN____9_SM', 0.256),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_XdPu', 'IEEE57_GEN____9_SM', 2.81),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_XpdPu', 'IEEE57_GEN____9_SM', 0.509),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_XppdPu', 'IEEE57_GEN____9_SM', 0.354),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_Tpd0', 'IEEE57_GEN____9_SM', 10.041),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_Tppd0', 'IEEE57_GEN____9_SM', 0.065),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_XqPu', 'IEEE57_GEN____9_SM', 2.62),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_XpqPu', 'IEEE57_GEN____9_SM', 0.601),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_XppqPu', 'IEEE57_GEN____9_SM', 0.377),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_Tpq0', 'IEEE57_GEN____9_SM', 1.21),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_Tppq0', 'IEEE57_GEN____9_SM', 0.094),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_UNom', 'IEEE57_GEN____9_SM', 20),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_SNom', 'IEEE57_GEN____9_SM', 1650),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_PNomTurb', 'IEEE57_GEN____9_SM', 1485),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_PNomAlt', 'IEEE57_GEN____9_SM', 1485),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_SnTfo', 'IEEE57_GEN____9_SM', 1650),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_UNomHV', 'IEEE57_GEN____9_SM', 69),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_UNomLV', 'IEEE57_GEN____9_SM', 20),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_UBaseHV', 'IEEE57_GEN____9_SM', 69),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_UBaseLV', 'IEEE57_GEN____9_SM', 20),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_RTfPu', 'IEEE57_GEN____9_SM', 0.0),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_XTfPu', 'IEEE57_GEN____9_SM', 0.1),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'governor_KGover', 'IEEE57_GEN____9_SM', 5),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'governor_PMin', 'IEEE57_GEN____9_SM', 0),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'governor_PMax', 'IEEE57_GEN____9_SM', 1008),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'governor_PNom', 'IEEE57_GEN____9_SM', 1008),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'Pm_ValueIn', 'IEEE57_GEN____9_SM', 0),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'URef_ValueIn', 'IEEE57_GEN____9_SM', 0),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'voltageRegulator_EfdMinPu', 'IEEE57_GEN____9_SM', -5),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'voltageRegulator_EfdMaxPu', 'IEEE57_GEN____9_SM', 5),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'voltageRegulator_UsRefMinPu', 'IEEE57_GEN____9_SM', 0.8),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'voltageRegulator_UsRefMaxPu', 'IEEE57_GEN____9_SM', 1.5),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'voltageRegulator_Gain', 'IEEE57_GEN____9_SM', 20),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'voltageRegulator_LagEfdMin', 'IEEE57_GEN____9_SM', 0),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'voltageRegulator_LagEfdMax', 'IEEE57_GEN____9_SM', 0);

INSERT INTO model_parameters (group_name, group_type, model_name, name, set_name)
VALUES ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_P0Pu', 'IEEE57_GEN____9_SM'),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_Q0Pu', 'IEEE57_GEN____9_SM'),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_U0Pu', 'IEEE57_GEN____9_SM'),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_UPhase0', 'IEEE57_GEN____9_SM');

INSERT INTO model_parameter_sets (group_name, group_type, model_name, name)
VALUES ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'IEEE57_GEN____1_SM');

INSERT INTO model_parameters (group_name, group_type, model_name, name, set_name, value_)
VALUES ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_ExcitationPu', 'IEEE57_GEN____1_SM', 1),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_md', 'IEEE57_GEN____1_SM', 0.05),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_mq', 'IEEE57_GEN____1_SM', 0.05),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_nd', 'IEEE57_GEN____1_SM', 9.285),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_nq', 'IEEE57_GEN____1_SM', 9.285),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_MdPuEfd', 'IEEE57_GEN____1_SM', 0),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_DPu', 'IEEE57_GEN____1_SM', 0),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_H', 'IEEE57_GEN____1_SM', 5.112),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_RaPu', 'IEEE57_GEN____1_SM', 0.003275),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_XlPu', 'IEEE57_GEN____1_SM', 0.265),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_XdPu', 'IEEE57_GEN____1_SM', 2.91),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_XpdPu', 'IEEE57_GEN____1_SM', 0.527),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_XppdPu', 'IEEE57_GEN____1_SM', 0.367),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_Tpd0', 'IEEE57_GEN____1_SM', 10.041),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_Tppd0', 'IEEE57_GEN____1_SM', 0.065),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_XqPu', 'IEEE57_GEN____1_SM', 2.72),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_XpqPu', 'IEEE57_GEN____1_SM', 0.623),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_XppqPu', 'IEEE57_GEN____1_SM', 0.391),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_Tpq0', 'IEEE57_GEN____1_SM', 1.22),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_Tppq0', 'IEEE57_GEN____1_SM', 0.094),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_UNom', 'IEEE57_GEN____1_SM', 20),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_SNom', 'IEEE57_GEN____1_SM', 1710),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_PNomTurb', 'IEEE57_GEN____1_SM', 1539),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_PNomAlt', 'IEEE57_GEN____1_SM', 1539),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_SnTfo', 'IEEE57_GEN____1_SM', 1710),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_UNomHV', 'IEEE57_GEN____1_SM', 69),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_UNomLV', 'IEEE57_GEN____1_SM', 20),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_UBaseHV', 'IEEE57_GEN____1_SM', 69),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_UBaseLV', 'IEEE57_GEN____1_SM', 20),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_RTfPu', 'IEEE57_GEN____1_SM', 0.0),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_XTfPu', 'IEEE57_GEN____1_SM', 0.1),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'governor_KGover', 'IEEE57_GEN____1_SM', 5),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'governor_PMin', 'IEEE57_GEN____1_SM', 0),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'governor_PMax', 'IEEE57_GEN____1_SM', 1539),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'governor_PNom', 'IEEE57_GEN____1_SM', 1539),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'Pm_ValueIn', 'IEEE57_GEN____1_SM', 0),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'URef_ValueIn', 'IEEE57_GEN____1_SM', 0),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'voltageRegulator_EfdMinPu', 'IEEE57_GEN____1_SM', -5),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'voltageRegulator_EfdMaxPu', 'IEEE57_GEN____1_SM', 5),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'voltageRegulator_UsRefMinPu', 'IEEE57_GEN____1_SM', 0.8),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'voltageRegulator_UsRefMaxPu', 'IEEE57_GEN____1_SM', 1.5),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'voltageRegulator_Gain', 'IEEE57_GEN____1_SM', 20),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'voltageRegulator_LagEfdMin', 'IEEE57_GEN____1_SM', 0),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'voltageRegulator_LagEfdMax', 'IEEE57_GEN____1_SM', 0);

INSERT INTO model_parameters (group_name, group_type, model_name, name, set_name)
VALUES ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_P0Pu', 'IEEE57_GEN____1_SM'),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_Q0Pu', 'IEEE57_GEN____1_SM'),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_U0Pu', 'IEEE57_GEN____1_SM'),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_UPhase0', 'IEEE57_GEN____1_SM');

INSERT INTO model_parameter_sets (group_name, group_type, model_name, name)
VALUES ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'IEEE57_GEN____12_SM');

INSERT INTO model_parameters (group_name, group_type, model_name, name, set_name, value_)
VALUES ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_ExcitationPu', 'IEEE57_GEN____12_SM', 1),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_md', 'IEEE57_GEN____12_SM', 0.05),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_mq', 'IEEE57_GEN____12_SM', 0.05),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_nd', 'IEEE57_GEN____12_SM', 9.285),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_nq', 'IEEE57_GEN____12_SM', 9.285),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_MdPuEfd', 'IEEE57_GEN____12_SM', 0),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_DPu', 'IEEE57_GEN____12_SM', 0),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_H', 'IEEE57_GEN____12_SM', 5.112),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_RaPu', 'IEEE57_GEN____12_SM', 0.003275),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_XlPu', 'IEEE57_GEN____12_SM', 0.265),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_XdPu', 'IEEE57_GEN____12_SM', 2.91),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_XpdPu', 'IEEE57_GEN____12_SM', 0.527),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_XppdPu', 'IEEE57_GEN____12_SM', 0.367),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_Tpd0', 'IEEE57_GEN____12_SM', 10.041),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_Tppd0', 'IEEE57_GEN____12_SM', 0.065),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_XqPu', 'IEEE57_GEN____12_SM', 2.72),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_XpqPu', 'IEEE57_GEN____12_SM', 0.623),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_XppqPu', 'IEEE57_GEN____12_SM', 0.391),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_Tpq0', 'IEEE57_GEN____12_SM', 1.22),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_Tppq0', 'IEEE57_GEN____12_SM', 0.094),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_UNom', 'IEEE57_GEN____12_SM', 20),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_SNom', 'IEEE57_GEN____12_SM', 1710),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_PNomTurb', 'IEEE57_GEN____12_SM', 1539),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_PNomAlt', 'IEEE57_GEN____12_SM', 1539),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_SnTfo', 'IEEE57_GEN____12_SM', 1710),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_UNomHV', 'IEEE57_GEN____12_SM', 69),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_UNomLV', 'IEEE57_GEN____12_SM', 20),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_UBaseHV', 'IEEE57_GEN____12_SM', 69),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_UBaseLV', 'IEEE57_GEN____12_SM', 20),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_RTfPu', 'IEEE57_GEN____12_SM', 0.0),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_XTfPu', 'IEEE57_GEN____12_SM', 0.1),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'governor_KGover', 'IEEE57_GEN____12_SM', 5),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'governor_PMin', 'IEEE57_GEN____12_SM', 0),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'governor_PMax', 'IEEE57_GEN____12_SM', 1539),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'governor_PNom', 'IEEE57_GEN____12_SM', 1539),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'Pm_ValueIn', 'IEEE57_GEN____12_SM', 0),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'URef_ValueIn', 'IEEE57_GEN____12_SM', 0),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'voltageRegulator_EfdMinPu', 'IEEE57_GEN____12_SM', -5),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'voltageRegulator_EfdMaxPu', 'IEEE57_GEN____12_SM', 5),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'voltageRegulator_UsRefMinPu', 'IEEE57_GEN____12_SM', 0.8),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'voltageRegulator_UsRefMaxPu', 'IEEE57_GEN____12_SM', 1.5),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'voltageRegulator_Gain', 'IEEE57_GEN____12_SM', 20),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'voltageRegulator_LagEfdMin', 'IEEE57_GEN____12_SM', 0),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'voltageRegulator_LagEfdMax', 'IEEE57_GEN____12_SM', 0);

INSERT INTO model_parameters (group_name, group_type, model_name, name, set_name)
VALUES ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_P0Pu', 'IEEE57_GEN____12_SM'),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_Q0Pu', 'IEEE57_GEN____12_SM'),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_U0Pu', 'IEEE57_GEN____12_SM'),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_UPhase0', 'IEEE57_GEN____12_SM');

INSERT INTO model_parameter_sets (group_name, group_type, model_name, name)
VALUES ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'IEEE57_GEN____3_SM');

INSERT INTO model_parameters (group_name, group_type, model_name, name, set_name, value_)
VALUES ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_ExcitationPu', 'IEEE57_GEN____3_SM', 1),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_md', 'IEEE57_GEN____3_SM', 0.215),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_mq', 'IEEE57_GEN____3_SM', 0.215),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_nd', 'IEEE57_GEN____3_SM', 6.995),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_nq', 'IEEE57_GEN____3_SM', 6.995),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_MdPuEfd', 'IEEE57_GEN____3_SM', 0),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_DPu', 'IEEE57_GEN____3_SM', 0),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_H', 'IEEE57_GEN____3_SM', 5.4),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_RaPu', 'IEEE57_GEN____3_SM', 0.002796),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_XlPu', 'IEEE57_GEN____3_SM', 0.202),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_XdPu', 'IEEE57_GEN____3_SM', 2.22),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_XpdPu', 'IEEE57_GEN____3_SM', 0.384),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_XppdPu', 'IEEE57_GEN____3_SM', 0.264),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_Tpd0', 'IEEE57_GEN____3_SM', 8.094),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_Tppd0', 'IEEE57_GEN____3_SM', 0.08),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_XqPu', 'IEEE57_GEN____3_SM', 2.22),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_XpqPu', 'IEEE57_GEN____3_SM', 0.262),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_XppqPu', 'IEEE57_GEN____3_SM', 0.26),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_Tpq0', 'IEEE57_GEN____3_SM', 1.572),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_Tppq0', 'IEEE57_GEN____3_SM', 0.084),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_UNom', 'IEEE57_GEN____3_SM', 24),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_SNom', 'IEEE57_GEN____3_SM', 1211),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_PNomTurb', 'IEEE57_GEN____3_SM', 1090),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_PNomAlt', 'IEEE57_GEN____3_SM', 1090),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_SnTfo', 'IEEE57_GEN____3_SM', 1211),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_UNomHV', 'IEEE57_GEN____3_SM', 69),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_UNomLV', 'IEEE57_GEN____3_SM', 24),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_UBaseHV', 'IEEE57_GEN____3_SM', 69),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_UBaseLV', 'IEEE57_GEN____3_SM', 24),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_RTfPu', 'IEEE57_GEN____3_SM', 0.0),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_XTfPu', 'IEEE57_GEN____3_SM', 0.1),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'governor_KGover', 'IEEE57_GEN____3_SM', 5),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'governor_PMin', 'IEEE57_GEN____3_SM', 0),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'governor_PMax', 'IEEE57_GEN____3_SM', 1090),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'governor_PNom', 'IEEE57_GEN____3_SM', 1090),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'Pm_ValueIn', 'IEEE57_GEN____3_SM', 0),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'URef_ValueIn', 'IEEE57_GEN____3_SM', 0),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'voltageRegulator_EfdMinPu', 'IEEE57_GEN____3_SM', -5),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'voltageRegulator_EfdMaxPu', 'IEEE57_GEN____3_SM', 5),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'voltageRegulator_UsRefMinPu', 'IEEE57_GEN____3_SM', 0.8),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'voltageRegulator_UsRefMaxPu', 'IEEE57_GEN____3_SM', 1.5),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'voltageRegulator_Gain', 'IEEE57_GEN____3_SM', 20),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'voltageRegulator_LagEfdMin', 'IEEE57_GEN____3_SM', 0),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'voltageRegulator_LagEfdMax', 'IEEE57_GEN____3_SM', 0);

INSERT INTO model_parameters (group_name, group_type, model_name, name, set_name)
VALUES ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_P0Pu', 'IEEE57_GEN____3_SM'),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_Q0Pu', 'IEEE57_GEN____3_SM'),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_U0Pu', 'IEEE57_GEN____3_SM'),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_UPhase0', 'IEEE57_GEN____3_SM');

INSERT INTO model_parameter_sets (group_name, group_type, model_name, name)
VALUES ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'IEEE57_GEN____8_SM');

INSERT INTO model_parameters (group_name, group_type, model_name, name, set_name, value_)
VALUES ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_ExcitationPu', 'IEEE57_GEN____8_SM', 1),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_md', 'IEEE57_GEN____8_SM', 0.215),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_mq', 'IEEE57_GEN____8_SM', 0.215),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_nd', 'IEEE57_GEN____8_SM', 6.995),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_nq', 'IEEE57_GEN____8_SM', 6.995),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_MdPuEfd', 'IEEE57_GEN____8_SM', 0),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_DPu', 'IEEE57_GEN____8_SM', 0),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_H', 'IEEE57_GEN____8_SM', 5.4),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_RaPu', 'IEEE57_GEN____8_SM', 0.002796),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_XlPu', 'IEEE57_GEN____8_SM', 0.202),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_XdPu', 'IEEE57_GEN____8_SM', 2.22),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_XpdPu', 'IEEE57_GEN____8_SM', 0.384),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_XppdPu', 'IEEE57_GEN____8_SM', 0.264),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_Tpd0', 'IEEE57_GEN____8_SM', 8.094),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_Tppd0', 'IEEE57_GEN____8_SM', 0.08),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_XqPu', 'IEEE57_GEN____8_SM', 2.22),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_XpqPu', 'IEEE57_GEN____8_SM', 0.262),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_XppqPu', 'IEEE57_GEN____8_SM', 0.26),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_Tpq0', 'IEEE57_GEN____8_SM', 1.572),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_Tppq0', 'IEEE57_GEN____8_SM', 0.084),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_UNom', 'IEEE57_GEN____8_SM', 24),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_SNom', 'IEEE57_GEN____8_SM', 1211),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_PNomTurb', 'IEEE57_GEN____8_SM', 1090),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_PNomAlt', 'IEEE57_GEN____8_SM', 1090),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_SnTfo', 'IEEE57_GEN____8_SM', 1211),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_UNomHV', 'IEEE57_GEN____8_SM', 69),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_UNomLV', 'IEEE57_GEN____8_SM', 24),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_UBaseHV', 'IEEE57_GEN____8_SM', 69),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_UBaseLV', 'IEEE57_GEN____8_SM', 24),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_RTfPu', 'IEEE57_GEN____8_SM', 0.0),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_XTfPu', 'IEEE57_GEN____8_SM', 0.1),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'governor_KGover', 'IEEE57_GEN____8_SM', 5),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'governor_PMin', 'IEEE57_GEN____8_SM', 0),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'governor_PMax', 'IEEE57_GEN____8_SM', 1090),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'governor_PNom', 'IEEE57_GEN____8_SM', 1090),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'Pm_ValueIn', 'IEEE57_GEN____8_SM', 0),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'URef_ValueIn', 'IEEE57_GEN____8_SM', 0),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'voltageRegulator_EfdMinPu', 'IEEE57_GEN____8_SM', -5),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'voltageRegulator_EfdMaxPu', 'IEEE57_GEN____8_SM', 5),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'voltageRegulator_UsRefMinPu', 'IEEE57_GEN____8_SM', 0.8),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'voltageRegulator_UsRefMaxPu', 'IEEE57_GEN____8_SM', 1.5),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'voltageRegulator_Gain', 'IEEE57_GEN____8_SM', 20),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'voltageRegulator_LagEfdMin', 'IEEE57_GEN____8_SM', 0),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'voltageRegulator_LagEfdMax', 'IEEE57_GEN____8_SM', 0);

INSERT INTO model_parameters (group_name, group_type, model_name, name, set_name)
VALUES ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_P0Pu', 'IEEE57_GEN____8_SM'),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_Q0Pu', 'IEEE57_GEN____8_SM'),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_U0Pu', 'IEEE57_GEN____8_SM'),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_UPhase0', 'IEEE57_GEN____8_SM');

INSERT INTO model_parameter_sets (group_name, group_type, model_name, name)
VALUES ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'IEEE57_GEN____2_SM');

INSERT INTO model_parameters (group_name, group_type, model_name, name, set_name, value_)
VALUES ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_ExcitationPu', 'IEEE57_GEN____2_SM', 1),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_md', 'IEEE57_GEN____2_SM', 0.05),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_mq', 'IEEE57_GEN____2_SM', 0.05),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_nd', 'IEEE57_GEN____2_SM', 9.285),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_nq', 'IEEE57_GEN____2_SM', 9.285),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_MdPuEfd', 'IEEE57_GEN____2_SM', 0),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_DPu', 'IEEE57_GEN____2_SM', 0),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_H', 'IEEE57_GEN____2_SM', 5.625),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_RaPu', 'IEEE57_GEN____2_SM', 0.00316),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_XlPu', 'IEEE57_GEN____2_SM', 0.256),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_XdPu', 'IEEE57_GEN____2_SM', 2.81),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_XpdPu', 'IEEE57_GEN____2_SM', 0.509),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_XppdPu', 'IEEE57_GEN____2_SM', 0.354),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_Tpd0', 'IEEE57_GEN____2_SM', 10.041),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_Tppd0', 'IEEE57_GEN____2_SM', 0.065),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_XqPu', 'IEEE57_GEN____2_SM', 2.62),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_XpqPu', 'IEEE57_GEN____2_SM', 0.601),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_XppqPu', 'IEEE57_GEN____2_SM', 0.377),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_Tpq0', 'IEEE57_GEN____2_SM', 1.21),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_Tppq0', 'IEEE57_GEN____2_SM', 0.094),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_UNom', 'IEEE57_GEN____2_SM', 20),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_SNom', 'IEEE57_GEN____2_SM', 1650),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_PNomTurb', 'IEEE57_GEN____2_SM', 1485),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_PNomAlt', 'IEEE57_GEN____2_SM', 1485),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_SnTfo', 'IEEE57_GEN____2_SM', 1650),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_UNomHV', 'IEEE57_GEN____2_SM', 69),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_UNomLV', 'IEEE57_GEN____2_SM', 20),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_UBaseHV', 'IEEE57_GEN____2_SM', 69),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_UBaseLV', 'IEEE57_GEN____2_SM', 20),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_RTfPu', 'IEEE57_GEN____2_SM', 0.0),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_XTfPu', 'IEEE57_GEN____2_SM', 0.1),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'governor_KGover', 'IEEE57_GEN____2_SM', 5),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'governor_PMin', 'IEEE57_GEN____2_SM', 0),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'governor_PMax', 'IEEE57_GEN____2_SM', 1485),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'governor_PNom', 'IEEE57_GEN____2_SM', 1485),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'Pm_ValueIn', 'IEEE57_GEN____2_SM', 0),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'URef_ValueIn', 'IEEE57_GEN____2_SM', 0),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'voltageRegulator_EfdMinPu', 'IEEE57_GEN____2_SM', -5),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'voltageRegulator_EfdMaxPu', 'IEEE57_GEN____2_SM', 5),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'voltageRegulator_UsRefMinPu', 'IEEE57_GEN____2_SM', 0.8),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'voltageRegulator_UsRefMaxPu', 'IEEE57_GEN____2_SM', 1.5),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'voltageRegulator_Gain', 'IEEE57_GEN____2_SM', 20),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'voltageRegulator_LagEfdMin', 'IEEE57_GEN____2_SM', 0),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'voltageRegulator_LagEfdMax', 'IEEE57_GEN____2_SM', 0);

INSERT INTO model_parameters (group_name, group_type, model_name, name, set_name)
VALUES ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_P0Pu', 'IEEE57_GEN____2_SM'),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_Q0Pu', 'IEEE57_GEN____2_SM'),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_U0Pu', 'IEEE57_GEN____2_SM'),
       ('IEEE57', 1, 'GeneratorSynchronousFourWindingsProportionalRegulations', 'generator_UPhase0', 'IEEE57_GEN____2_SM');
